{
    { let a_9999999999999999999999999999999999999999999999999999 }
    { let a_9999999999999999999999999999999999999999999999999999 }
    { let b_999999999 }
    { let b_999999999 }
    { let b_999999999 }
    { let b_999999999 }
    { let b_999999999 }
	{ let c_3 }
	{ let c_4 }
	{ let c_5 }
}
// ----
// disambiguator
// {
//     {
//         let a_9999999999999999999999999999999999999999999999999999
//     }
//     {
//         let a_9999999999999999999999999999999999999999999999999999_1
//     }
//     {
//         let b
//     }
//     {
//         let b_1
//     }
//     {
//         let b_2
//     }
//     {
//         let b_3
//     }
//     {
//         let b_4
//     }
//     {
//         let c
//     }
//     {
//         let c_1
//     }
//     {
//         let c_2
//     }
// }
